# Generated by Django 5.1.4 on 2025-01-25 05:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="catagory",
            name="icon",
            field=models.FileField(
                blank=True, null=True, upload_to=api.models.catagory_icon_upload_path
            ),
        ),
    ]
